export type {
  RawNeteaseResponse as NeteaseResponse,
  RawQrKeyData as QrKeyResponse,
  RawQrCheckResponse as QrCheckResponse,
  UserProfile,
  UserPlaylist,
  PlaylistDetail,
  SongDetail,
  NeteaseSearchResult as SearchResult,
  RecommendPlaylist,
  Toplist,
  AlbumDetail,
  ArtistDetail,
  ResolveUrlResult,
} from "@otter-music/shared";
